-- MySQL Script generated by MySQL Workbench
-- jeu. 06 janv. 2022 19:33:19 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema imit_chef
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imit_chef
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imit_chef` DEFAULT CHARACTER SET latin1 ;
USE `imit_chef` ;

-- -----------------------------------------------------
-- Table `imit_chef`.`Candidates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imit_chef`.`Candidates` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `reciepes` VARCHAR(255) NOT NULL,
  `tv_show` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `imit_chef`.`Tv_show`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imit_chef`.`Tv_show` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `category` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `imit_chef`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imit_chef`.`Users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `imit_chef`.`Candidates_has_Tv_show`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imit_chef`.`Candidates_has_Tv_show` (
  `Candidates_id` INT(11) NOT NULL,
  `Tv_show_id` INT(11) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`Candidates_id`, `Tv_show_id`),
  INDEX `fk_Candidates_has_Tv_show_Tv_show1_idx` (`Tv_show_id` ASC),
  INDEX `fk_Candidates_has_Tv_show_Candidates1_idx` (`Candidates_id` ASC),
  CONSTRAINT `fk_Candidates_has_Tv_show_Candidates1`
    FOREIGN KEY (`Candidates_id`)
    REFERENCES `imit_chef`.`Candidates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidates_has_Tv_show_Tv_show1`
    FOREIGN KEY (`Tv_show_id`)
    REFERENCES `imit_chef`.`Tv_show` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `imit_chef`.`Reciepes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imit_chef`.`Reciepes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imit_chef`.`Candidates_has_Reciepes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imit_chef`.`Candidates_has_Reciepes` (
  `Candidates_id` INT(11) NOT NULL,
  `Reciepes_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`Candidates_id`, `Reciepes_id`),
  INDEX `fk_Candidates_has_Reciepes_Reciepes1_idx` (`Reciepes_id` ASC),
  INDEX `fk_Candidates_has_Reciepes_Candidates1_idx` (`Candidates_id` ASC),
  CONSTRAINT `fk_Candidates_has_Reciepes_Candidates1`
    FOREIGN KEY (`Candidates_id`)
    REFERENCES `imit_chef`.`Candidates` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Candidates_has_Reciepes_Reciepes1`
    FOREIGN KEY (`Reciepes_id`)
    REFERENCES `imit_chef`.`Reciepes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `imit_chef`.`Users_has_Reciepes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imit_chef`.`Users_has_Reciepes` (
  `Users_id` INT(11) NOT NULL,
  `Reciepes_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Users_id`, `Reciepes_id`),
  INDEX `fk_Users_has_Reciepes_Reciepes1_idx` (`Reciepes_id` ASC),
  INDEX `fk_Users_has_Reciepes_Users1_idx` (`Users_id` ASC),
  CONSTRAINT `fk_Users_has_Reciepes_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `imit_chef`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Reciepes_Reciepes1`
    FOREIGN KEY (`Reciepes_id`)
    REFERENCES `imit_chef`.`Reciepes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
